# Pregunta 2

<a id="segundo"></a>
## 2. Job Salary Prediction

En esta sección se trabajará con el problema de predecir el salario que ofrece un anuncio en internet a través unicamente del texto del anuncio. El dataset es ofrecido por *Adzuna* como una competencia en la plataforma más grande de *data science* Kaggle, a través del siguiente __[link](https://www.kaggle.com/c/job-salary-prediction)__. El objetivo de la competencia, según *Adzuna*, es el de tener un motor que pueda predecir el salario de cualquier anuncio de trabajo en Reunio Unido, para poder mejorar la experiencia de los usuarios que buscan trabajos, ya que así pueden filtrar sin que el mismo empleador señale explícitamente cuánto paga.

<img src="http://s5047.pcdn.co/wp-content/uploads/2013/05/salary-prediction-engine-v2.png" title="Title text" width="50%"/>

La métrica de evaluación de la competencia es MAE (*mean absolute error*):

$$
L = \frac{1}{N} \sum_i^N  \mid y_i - \hat{y}_i \mid
$$


Para descargar los datos a utilizar (*Train_rev1*) debe estar registrado en la plataforma de Kaggle. Se cuenta con cientos de miles registros con textos sin procesar, es decir, no están estructurados.


> a) Carge los datos *csv* de entrenamiento y cree un conjunto de validación con los últimos 10 mil datos en un dataframe de *pandas*. Describa los datos, apóyese de gráficos ¿Cuántos datos hay en cada conjunto?  
```python
import pandas as pd
df = pd.read_csv("Train_rev1.csv")
df_train = df.iloc[:-10000]
df_val = df.iloc[-10000:]
...#load other sets
df.head()
```
*Recuerde que si no puede trabajar con todos los datos, debido a su volumen, puede muestrear*.


> b) Extraiga los datos de cada conjunto con los que trabajará, el *input* $X$, los textos, y el *output* $y$, los salarios.
```python
text = df.FullDescription
salary = df.SalaryNormalized
```

> c) Realice un pre-procesamiento a los datos brutos de texto para extraer características y generar la representación de los datos de entrada al modelo $\vec{x}$. Comente sobre lo realizado.

> d) Intente resolver el problema enfrentándolo como regresión con el modelo de regresión lineal ordinaria en *sklearn*. ¿Qué es lo que hace *fit_intercept=True*? Evalúe la función objetivo (F.O.) utilizada y la métrica de la competencia (*mean absolute error*) en ambos conjuntos generados en el punto a). Comente lo observado.
```python
from sklearn.linear_model import LinearRegression as LR
model = LR(fit_intercept=True, normalize=False)
model.fit(X_train,y_train)
... #measure F.O.
from sklearn.metrics import mean_absolute_error #measure MAE
print("MAE on train: ",mean_absolute_error(y_train, model.predict(X_train)))
print("MAE on validation: ",mean_absolute_error(y_val, model.predict(X_val)))
```

> e) Intente mejorar sus resultados en base a la métrica de la competencia (MAE) sobre el conjunto de validación. Comente sobre lo realizado.  
*No se le pide que imite los resultados ganadores de la competencia (MAE de 3400), sino que mejore lo ya alcanzado siendo creativo.*
<div class="alert alert-warning"> HINT: Una opción es cambiar el *approach* de resolución desde regresión a casificación o trabajo sobre los datos (tal como limpiarlos).</div>


In [3]:
# parte a:

import pandas as pd

df = pd.read_csv("Train_rev1.csv") # dataset completo
#df = pd.read_csv("Train_rev1.csv", skiprows = 234768) # 244768 filas de datos en el .csv
#df_train = df.iloc[:-10000]
#df_val = df.iloc[-10000:]
...#load other sets
#df.head()

244768


Los atributos del dataset son:

Id:

Title:

FullDescription:

LocationRaw:


In [21]:
#parte b:

text = df.FullDescription
salary = df.SalaryNormalized
category = df.Category
contractType = df.ContractType
contractTime = df.ContractTime
localization = df.LocationNormalized
company = df.Company


Bla bla.

In [17]:
#parte c:

df['FullDescription'][1]
df.head(20)

Id                                              Title  \
0   12612628                        Engineering Systems Analyst   
1   12612830                            Stress Engineer Glasgow   
2   12612844                   Modelling and simulation analyst   
3   12613049  Engineering Systems Analyst / Mathematical Mod...   
4   12613647         Pioneer, Miser Engineering Systems Analyst   
5   13179816         Engineering Systems Analyst Water Industry   
6   14131336          Senior Subsea Pipeline Integrity Engineer   
7   14663196  RECRUITMENT CONSULTANT  INDUSTRIAL / COMMERCIA...   
8   14663197  RECRUITMENT CONSULTANT  CONSTRUCTION / TECHNIC...   
9   15395797                             Subsea Cables Engineer   
10  19047429            Trainee Mortgage Advisor  East Midlands   
11  20199757                   PROJECT ENGINEER, PHARMACEUTICAL   
12  20638787                Principal Composite Stress Engineer   
13  20638788           Senior Fatigue Damage Tolerance Engineer   
14  20797143  Chef de Partie  Award Winning Restaurant  Exce...   
15  22579462                                   Quality Engineer   
16  22581547                        Principal Controls Engineer   
17  22933091  Chef de Partie  Award Winning Dining  Live In ...   
18  23528672       Senior Fatigue and Damage Tolerance Engineer   
19  23529949                                C I Design Engineer   

                                      FullDescription  \
0   Engineering Systems Analyst Dorking Surrey Sal...   
1   Stress Engineer Glasgow Salary **** to **** We...   
2   Mathematical Modeller / Simulation Analyst / O...   
3   Engineering Systems Analyst / Mathematical Mod...   
4   Pioneer, Miser  Engineering Systems Analyst Do...   
5   Engineering Systems Analyst Water Industry Loc...   
6   A globally renowned engineering and training c...   
7   THIS IS A LIVE VACANCY NOT A GENERIC ADVERTISE...   
8   This is an exceptional opportunity to join a c...   
9   A subsea engineering company is looking for an...   
10  Are you a successful, results driven person? A...   
11  PROJECT ENGINEER PHAMACEUTICAL, c****  Excelle...   
12  Aerospace Senior Composite Structures Engineer...   
13  Senior Fatigue Static stress (metallic or comp...   
14  A well respected restaurant located in the Der...   
15  Our client are a leading supplier of precision...   
16  A leading Subsea Engineering Company require a...   
17  A popular hotel located in Norfolk which is a ...   
18  Senior Fatigue Static stress (metallic or comp...   
19  We are currently recruiting on behalf of our c...   

                          LocationRaw LocationNormalized ContractType  \
0             Dorking, Surrey, Surrey            Dorking          NaN   
1         Glasgow, Scotland, Scotland            Glasgow          NaN   
2   Hampshire, South East, South East          Hampshire          NaN   
3      Surrey, South East, South East             Surrey          NaN   
4      Surrey, South East, South East             Surrey          NaN   
5     Dorking, Surrey, Surrey, Surrey            Dorking          NaN   
6                   Aberdeen, Borders                 UK          NaN   
7      MANCHESTER, Greater Manchester         Manchester          NaN   
8               LEEDS, West Yorkshire              Leeds          NaN   
9                        Aberdeen, UK           Aberdeen          NaN   
10                      East Midlands      East Midlands          NaN   
11                Witney, Oxfordshire             Witney          NaN   
12                   Avon, South West               Avon          NaN   
13                   Avon, South West               Avon          NaN   
14     Derby Derbyshire East Midlands              Derby          NaN   
15           Gateshead, Tyne and Wear          Gateshead          NaN   
16                   Kent, South East               Kent          NaN   
17                Norfolk East Anglia                 UK          NaN   
18               

In [24]:
df['ContractType'].value_counts()

full_time    57538
part_time     7904
Name: ContractType, dtype: int64

<a id="tercero"></a>
## 3. Linear Regression by hand

En esta sección se le pedirá que implemente la regresión lineal ordinaria a través del algoritmo SGD (*Stochastic Gradient Descend*) para encontrar los parámetros de la regresión a través de este algoritmo de manera iterativa. La técnica de SGD es sin duda dominante al momento de entrenar modelos en máquinas de aprendizaje cuando la solución no tiene un óptimo derivable analíticamente, en este caso la regresión lineal ordinaria que trabajaremos si tiene óptimo anaĺitico, sin embargo, se le pedirá que compare este caso con fines pedagógicos.

* Regresión lineal ordinaria:
$$
\hat{y} = f(\vec{x}) =\vec{\beta}^T\cdot \vec{x}
$$

* Función objetivo:
$$
Loss = \frac{1}{N} \sum_i^N ( y_i - \hat{y}_i )^2
$$


* Algoritmo SGD para regresión lineal ordinaria:
$$ \vec{\beta}^{(t+1)} \leftarrow \vec{\beta}^{(t)} - \eta \nabla_{\vec{\beta}^{(t)}} Loss $$

Para lo que sigue de la actividad sólo podrá utilizar *numpy* (para operaciones de algebra lineal).

> a) Escriba una función que calcule la función de pérdida, error cuadrático medio (MSE - *mean squared error*), para un dato o para un conjunto de datos.

> b) Escriba una función que calcule el gradiente (derivada) de la función de pérdida anterior, para un dato o para un conjunto de datos. *Escriba explícitamente la derivada (gradiente)*.

> c) Escriba una función que calcule los parámetros de una regresión lineal simple de manera analítica (es decir el mínimo global). 

<div class="alert alert-warning"> Hint: ésto debería ser la ecuación desglosada de la derivada igual a 0, la cual incluye $(X^TX)^{-1}$</div>


> d) Ahora escriba un programa que permita entrenar una regresión lineal a través del algoritmo SGD mostrado en la ecuación del algoritmo SGD, es decir, que de manera iterativa, vaya tomando un dato a la vez, y actualizando el parámetro $\beta$ a través del gradiente descendiente de la función de pérdida de la regresión lineal ordinaria, de la pregunta b).

> e) Demuestre que sus programas funcionan en un problema de regresión simple. Para esto utilice el dataset **Boston Housing** , disponible a través de la librería __[*sklearn*](http://scikit-learn.org)__, el cual corresponde a el precio de diferentes casas en Boston además de distintas características relevantes respecto al lugar, como por ejemplo el crimen en la ciudad, el número de habitaciones, que tan vieja es, distancia a lugares relevantes, entre otros. Éstas características deben combinarse linealmente para estimar el precio de la casa.
<div class="alert alert-block alert-info">Es una buena práctica el normalizar los datos antes de trabajar con el modelo</div>

```python
from sklearn.datasets import load_boston
X_train,y_train = load_boston(return_X_y=True)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
```
Para evaluar los resultados, construya un gráfico correspondiente a la función de pérdida utilizada en el entrenamiento *versus* número de iteraciones (**realice 1000 iteraciones**), utilizando sólo el conjunto de entrenamiento (el objetivo de esta sección es familiarizarse con el algoritmo). Además de reportar el tiempo de entrenamiento mediante el algoritmo implementado en c) y d).

> e) Varié la tasa de aprendizaje $\eta \in [0,1]$ del algoritmo SGD del punto d), compare los resultados entre sí y con la solución óptima encontrada en c). Comente.

In [21]:
#parte a
import numpy as np

#valores de prueba:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

betas = np.array([2,4,5])

y = np.array([52,63,74])

def reg(input_values,betas): #input_values es la matriz x de valores de entrada, betas son los que deben despejarse despues
    return np.dot(np.transpose(betas),input_values)

def regMATRIX(input_values,betas):
    return np.dot(input_values,betas)

def MSE(input_values,output,betas):
    predicted_values = reg(input_values,betas)
    N = len(output)
    suma = np.sum((output-predicted_values)**2)
    return (1/N)*suma

def MSEMATRIX(input_values,output,betas):
    predicted_values = regMATRIX(input_values,betas)
    N = len(betas)
    return(1/N)*np.linalg.norm(output - predicted_values)**2

#print(MSE(x,y,betas))
#print(MSEMATRIX(x,y,betas))
print(reg(x,betas))
print(regMATRIX(x,betas))

1.0
0.9999999999999998
[53 64 75]
[25 58 91]


Parte b:

Primero recordando el valor de la aproximación de y:

$$
\hat{y} = f(\vec{x}) =\vec{\beta}^T\cdot \vec{x}
$$

La derivada de la ecuación del MSE es:

$$
\nabla_{\vec{\beta}}Loss = \frac{1}{N}\nabla_{\vec{\beta}}\left(\sum_i^N ( y_i - \hat{y}_i )^2\right)
$$

$$
\nabla_{\vec{\beta}}\left(\sum_i^N ( y_i - \hat{y}_i )^2\right) = \nabla_{\vec{\beta}}\left(\sum_i^N (y_i^2 - 2y_i\vec{\beta}^T\vec{x} + (\vec{\beta}^T\vec{x})^2 ) \right)
$$

$$
\nabla_{\vec{\beta}}\left(\sum_i^N ( y_i - \hat{y}_i )^2\right) = 2\sum_i^N(\vec{\beta}^T\vec{x}_i^2 - y_i\vec{1}^T\vec{x}_i)
$$

$$
\nabla_{\vec{\beta}}\left(\sum_i^N ( y_i - \hat{y}_i )^2\right) = 2\sum_i^N(\vec{\beta}^T\vec{x}_i^2 - y_i||\vec{x}_i||_1)
$$

Reemplazando se llega a:

$$
\frac{\partial Loss}{\partial \beta} = \frac{1}{N}\frac{\partial}{\partial \beta}\left(\sum_i^N ( y_i - \hat{y}_i )^2\right) = \frac{2}{N}\sum_i^N(\vec{\beta}^T\vec{x}_i^2 - y_i||\vec{x}_i||_1)
$$

En forma matricial (sacado de las ppts):

Para quitar la sumatoria, el problema se puede escribir de manera matricial definiendo las siguientes matrices:
* Las respuestas deseadas se organizan como filas de una matriz $Y$ de dimensiones n x 1.
* Las incognitas $\beta_0,\beta_1,\beta_2$ se organizan en un vector $\vec{\beta}$ de dimension d+1.
* Los ejemplos de entrada se organizan como una matriz $X$ de dimensiones n x d+1.

Entonces la regresión lineal se puede escribir de la siguiente manera:

$$
    \hat{Y} = X*\vec{\beta}
$$

Y la ecuación de perdida se puede escribir como:

$$
    Loss = \frac{1}{N}||Y-\hat{Y}||^2
$$

Entonces el gradiente sera:

$$
    \nabla_{\vec{\beta}}Loss =\frac{1}{N} \nabla_{\vec{\beta}}||Y-\hat{Y}||^2
$$

$$
    \nabla_{\vec{\beta}}||Y-\hat{Y}||^2 = 2X^T(X\vec{\beta} - Y)
$$

Reemplazando:

$$
    \nabla_{\vec{\beta}}Loss = \frac{1}{N} 2X^T(X\vec{\beta} - Y)
$$

In [13]:

def MSEgradient(input_values,real_values,betas):
    N = len(real_values)
    suma = np.sum(np.dot(np.transpose(betas),input_values**2) - real_values*sum(input_values))
    return (1/N)*suma

def MSEgradientMATRIX(X,Y,beta): #X dim n x d+1, Y dim n x 1, beta es un vector, es decir dim d+1 x 1. 
    N = len(beta)
    return (2/N)*np.dot(np.transpose(X),(np.dot(X,beta) - Y))

print(MSEgradient(x,y,betas))
print(MSEgradientMATRIX(x,y,betas))

-531.6666666666666
[48. 38. 28.]


parte c:


